baseurl: ""
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      version_scope: "Sonderausgabe" 
      last_edit: "31. Dezember 1813"
plugins:
- jekyll-autoprefixer