baseurl: ""
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock", "node_modules"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      version_scope: "Globalausgabe" 
      last_edit: "28. Dezember 1814"
plugins:
- jekyll-autoprefixer