# Meta
title: Die Illustrierte
author: pojntfx
email: felicitas@pojtinger.com
description: >-
  Die Website des Freien Digitalen Schwarzen Bretts

# Config
baseurl: ""
url: "https://illustrierte.tk/"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      version_scope: "Sonderausgabe" 
      last_edit: "31. Dezember 1813"

# Plugins
plugins:
  - jekyll-admin
jekyll_admin:
  hidden_links:
    - datafiles # We do not have any data files currently